### ISSUE TITLE
Create public facing version of the project roadmap

### ISSUE THREAD

**Issue by harisood** [sa-tre/satre-team#23]
### Summary of issue

We have a roadmap for engaging stakeholders, Collaboration Cafes, and more. This should be cleaned up, and shared publicly on this repo

### What needs to be done?

- [ ] Create skeleton for public roadmap
- [ ] Populate roadmap with content
- [ ] Get feedback from SATRE team
- [ ] Make public on this repo

### Issue checklist

- [X] I have assigned the appropriate work package label to this issue, and added any other relevant labels
- [X] I have added this to the `SATRE backlog (public)` project board
- [X] I have assigned this issue to at least one person on the SATRE team

**Comment by manics** [comment]
We need a new SATRE roadmap, that should be public
