### ISSUE TITLE
Process SATRE feature questionnaire

### ISSUE THREAD

**Issue by edwardchalstrey1** [sa-tre/satre-team#9]
The SATRE feature questionnaire has been completed by ~100 participants and we need to decide how we will use this data to inform the SATRE specification doc design

### Tasks

- Decide processes by **Thursday 18th May**:
    - [x] Decide on collaboration method for processing SATRE feature questionnaire
    - [x] Split the survey into sections that could be worked on independently (see [here](https://github.com/sa-tre/satre-team/issues/9#issuecomment-1545948268))
      - [x] sa-tre/satre-team#11
      - [x] sa-tre/satre-team#12
      - [x] sa-tre/satre-team#16 
    - [x] sa-tre/satre-team#13
- Complete summary of results for each section by **later date**:
    - [x] sa-tre/satre-team#14
    - [x] sa-tre/satre-team#17
        - Depending on how much work is identified by sa-tre/satre-team#11 - this may need to be split into a new issue for each Q, or one person could do all of them
    - [x] sa-tre/satre-team#18
    - [x] sa-tre/satre-team#19

### Related tasks

- [x] sa-tre/satre-specification#72
- [x] sa-tre/satre-team#20 

### Extra notes

- [name=Jim] Being transparent about how the survey has influenced us and our decision process is important. Would be comfortable with us rejecting a popular item if we can justify it and we are open about that.
- [name=James G] For example, some 'essential' features may not be possible depending on TRE architecture, might be out-of-scope for SATRE _etc._
- [name=Chris] Agreed. _We_ make decisions, that is our role. Influenced by the community but also guided by our knowledge and expertise. We can overrule a decision, we need to make sure we are clear why.
- [name=Chris] Therefore, use the collaboration cafe to try and fill some of the gaps and address things the survey hasn't. That we we are prepared for version 0.0.1 of the spec.

**Comment by edwardchalstrey1** [comment]
[Ed's hackmd](https://hackmd.io/hDrPUl-6Rh6kcyoXdNJJpQ)

**Comment by edwardchalstrey1** [comment]
## Collaboration method for processing the survey data

See https://github.com/sa-tre/feature_survey/tree/main

**Comment by edwardchalstrey1** [comment]
@JimMadge @craddm @harisood If you want to make a start helping out, I suggest the following:

1. Select 1 or more of the tasks identified above, convert to an issue and assign yourself
2. ~~See the comment above on how to to load the survey results in Jupyter - perhaps the first person to try this can check out the `final-results` branch and merge [this PR](https://github.com/sa-tre/satre-notebooks-private/pull/2) since Simon is away~~

I assigned sa-tre/satre-team#13 to Hari, but others can contribute there too

**Comment by edwardchalstrey1** [comment]
# For collaboration cafe Thursday 18th May '23

- @harisood + @edwardchalstrey1 
   - Complete sa-tre/satre-team#11 
   - Progress as much as possible sa-tre/satre-team#17
- @craddm @JimMadge 
    - Complete sa-tre/satre-team#12
   - Progress as much as possible sa-tre/satre-team#18

**Comment by manics** [comment]
We took the survey into account, results are available for future reference
